# Generated by Django 4.2.13 on 2024-07-18 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slots', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='bait/')),
                ('red_modifier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('blue_modifier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('green_modifier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('yellow_modifier', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FishType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='location/')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slots', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('fish_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('fish_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField()),
                ('bait_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TackleBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slots', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('bait_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('location_id', models.IntegerField(null=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('image', models.ImageField(default='player/default.jpg', upload_to='player/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slots', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='fish/')),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coastapi.fishtype')),
            ],
        ),
    ]
